gems:
  - jekyll-sitemap
  - jekyll-relative-links

markdown: kramdown

permalink: pretty

kramdown:
  parse_block_html: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: /:year/:month/:day/:title

collections:
  annexes:
    output: true
    permalink: /:path/
  privexes:
    output: true
    permalink: /:path/
  fleat:
