markdown: kramdown

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

tabs:
  - title: "Principles"
    url: "/principles"
  - title: "Tools"
    url: "/tools"
  - title: "User guide"
    url: "/userguide"
  - title: "Pricing"
    url: "/pricing"
