title: Et ça vole ?!
description: Blog technique sur ce qui vole plus ou moins tout seul. Ou pas.
author:
  name: Vincent Jacques
  email: vincent@vincent-jacques.net

# These gems come from https://pages.github.com/versions/
gems:
  - jekyll-sitemap
  - jekyll-relative-links
  - jekyll-feed
  - jekyll-coffeescript

markdown: kramdown

permalink: pretty

kramdown:
  parse_block_html: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: /:year/:month/:day/:title

collections:
  annexes:
    output: true
    permalink: /:path/
  privexes:
    output: true
    permalink: /:path/
  fleat:

exclude:
  - README.md
  - run_development_cycle.sh
